# ----- 以下参数为常规配置，基本不需要修改 ----- #
# 图片总数
total_img_num: 21

# 原始图片主观分数，每个demo的第一个分数无效，占位作用
scores_original:
  "LG":
    - -1
    - 50
    - 53.33
    - 40
    - 40
    - 50
    - 50
    - 33.33
    - 40
    - 36.67
    - 53.33
    - 40
    - 40
    - 36.67
    - 46.67
    - 46.67
    - 36.67
    - 43.33
    - 50
    - 60
    - 53.33
    - 46.67

  "SONY":
    - -1
    - 60
    - 60
    - 53.33
    - 53.33
    - 53.33
    - 60
    - 56.67
    - 60
    - 63.33
    - 66.67
    - 63.33
    - 60
    - 40
    - 40
    - 56.67
    - 53.33
    - 50
    - 56.67
    - 56.67
    - 56.67
    - 60

  "AMAZON":
    - -1
    - 50
    - 50
    - 43.33
    - 33.33
    - 36.67
    - 40
    - 36.67
    - 36.67
    - 33.33
    - 26.67
    - 30
    - 33.33
    - 23.33
    - 40
    - 43.33
    - 50
    - 46.67
    - 53.33
    - 40
    - 33.33
    - 36.67

# 对于每个指标, 选择的是哪些图片进行扩充
# 第一个参数是demo名称, 第二个参数是图片序号
augment_data_demo:
  "qingxidu":
    - "LG"
    - 3
  "baipingheng":
    - "AMAZON"
    - 4
  "huijie":
    - "LG"
    - 7
  "caisebaohedu":
    - "AMAZON"
    - 10
  "caisezhunquexing":
    - "AMAZON"
    - 13
  "duibidu":
    - "LG"
    - 16
  "quyukongguang":
    - "AMAZON"
    - 20

# 图片序号和指标的对应关系
target_index_to_img_idx:
  "qingxidu":
    - 1
    - 3
  "baipingheng":
    - 4
    - 6
  "huijie":
    - 7
    - 9
  "caisebaohedu":
    - 10
    - 12
  "caisezhunquexing":
    - 13
    - 15
  "duibidu":
    - 16
    - 18
  "quyukongguang":
    - 19
    - 21

# 样品列表
demo_list:
  - "LG"
  - "SONY"
  - "AMAZON"

# 图片扩充生成的参数
augment_data_param:
  "qingxidu":
    - 1
    - 3
    - 5
  "baipingheng":
    - 10
    - 15
    - 20
  "huijie":
    - 1.5
    - 2.0
    - 2.5
  "caisebaohedu":
    - 0.75
    - 0.5
    - 0.25
  "caisezhunquexing":
    - 10
    - 15
    - 20
  "duibidu":
    - 1.2
    - 1.7
    - 2.2
  "quyukongguang":
    - 15
    - 25
    - 35

# 扩充数据集分数
scores_agumented:
  "qingxidu": # 原始：40
    - 35
    - 25
    - 10
  "baipingheng": # 原始：33.33
    - 21.63 # temperature从0到10
    - 15.78
    - 10 # 9.93 ≈ 10
  "huijie": # 原始：33.33
    - 25.53
    - 17.73
    - 10 # 9.93 ≈ 10
  "caisebaohedu": # 原始：26.67
    - 21.07
    - 15.47
    - 10 # 9.87 ≈ 10
  "caisezhunquexing": # 原始: 23.33
    - 16.63 # hue_offset从0到10
    - 13.28
    - 10 # 9.93 ≈ 10
  "duibidu": # 原始: 36.67
    - 32.22
    - 21.11
    - 10
  "quyukongguang": # 原始: 33.33
    - 21.67
    - 15.83
    - 10
